### ISSUE TITLE
update Go 1.10.4 to Go 1.12.6

### ISSUE THREAD

**Issue by yeya24** [pouchcontainer/pouchlinter#11]
Both Pouch and Dragonfly has upgraded to Go 1.12.6, they all depend this project to do ci. It is important to upgrade this image to Go 1.12.6 to do some `go mod` related check. @allencloud

**Comment by allencloud** [comment]
Quite reasonable. Could you submit a pull request to update this? @yeya24 
Then I will tag this, rebuild and push the image.

**Comment by allencloud** [comment]
I have updated the pouchcontainer/pouchlinter:v0.2.0 on DockerHub. @yeya24 

<img width="781" alt="屏幕快照 2019-07-04 上午11 06 46" src="https://user-images.githubusercontent.com/9465626/60637147-d84a6200-9e4b-11e9-8bf5-eaff851d7a55.png">
