### ISSUE TITLE
help use golangci-lint to replace DEPRECATED gometalinter 

### ISSUE THREAD

**Issue by allencloud** [pouchcontainer/pouchlinter#14]
Since [gometalinter](https://github.com/alecthomas/gometalinter) is DEPRECATED, so I think we should use https://github.com/golangci/golangci-lint to do the golang code checking.

Could you help to finish this in the Dockerfile of pouchlinter? @yeya24 
Thanks a lot.

**Comment by yeya24** [comment]
I' d like to work on this next week.
