### ISSUE TITLE
exec: "gcc": executable file not found in $PATH

### ISSUE THREAD

**Issue by hellolijj** [pouchcontainer/pouchlinter#17]
when i use pouchlinter image check my codes, it got error as list:
```
#!/bin/bash -eo pipefail
go fmt ./...
go vet ./...
# github.com/AliyunContainerService/gpu-scheduler-extender/vendor/github.com/NVIDIA/gpu-monitoring-tools/bindings/go/nvml
exec: "gcc": executable file not found in $PATH
Exited with code 2
```

but docker file has installed gcc `https://github.com/pouchcontainer/pouchlinter/blob/master/Dockerfile#L14-L18`

so, i build a new image, the probelm was solved.

maybe, image `pouchcontainer/pouchlinter` need update

**Comment by yeya24** [comment]
Yes. In my last PR, I add the installation of gcc because it is required by golangci-lint.
Seems like the pouchlinter image in docker hub is not synced with Github.

**Comment by allencloud** [comment]
Thanks for your report. @hellolijj @yeya24 
Sorry for the delay of pushing images. Now I have pushed to dockerhub. Please help to use `pouchcontainer/pouchlinter:v0.2.2`.

I have tested the image locally:
```
pouchlinter (master) # docker run -it pouchcontainer/pouchlinter:v0.2.2 bash
root@039703cf34c9:/# which gcc
/usr/bin/gcc
root@039703cf34c9:/# which golangci-lint
/go/bin/golangci-lint
root@039703cf34c9:/# exit
exit
pouchlinter (master) #
```
